### ISSUE TITLE
How to use api 'taobao.picture.upload' for fetching remote image and uploading with sdk?

### ISSUE THREAD

**Issue by phariel** [blacktail/taobao#6]
Hi @blacktail 
Sorry for bothering you.
我想请教一个问题，如下：
taobao.core.call({
          method: 'post'
        }, {
          method: 'taobao.picture.upload',
          picture_category_id: 0,
          image_input_title: imageName,
          img: imgByteArray
        }, function(body) {
          //...
        });

imgByteArray的地方该如何从远端获取一个图片然后转换成byte[] 对象？
我用request module https://github.com/mikeal/request 没有成功，还望指教。

**Comment by duzhenxun** [comment]
你最后怎么处理的？？

**Comment by phariel** [comment]
@duzhenxun 没有成功 我自己关掉了 而且是5年前提的问题了 也不适用于现在的版本 直接问作者
